name: Filter South Korea stations

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OSM tools
        run: sudo apt install osmium-tool osmctools

      - name: Install rust
        run: rustup toolchain install stable
        
      - name: "Download South Korea"
        uses: wei/wget@v1
        with:
          args: https://download.geofabrik.de/asia/south-korea-latest.osm.pbf

      - name: Filter South Korea for stations
        run: osmium tags-filter -o korea-stations-latest.osm.pbf --expressions=railway-station-filter.txt south-korea-latest.osm.pbf
  
      - name: "Upload South Korea stations filtered"
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: korea-stations-latest.osm.pbf
          ASSET_NAME: korea-stations-latest.osm.pbf
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''

      - name: Filter South Korea pfaedle general
        run: osmium tags-filter -o pfaedle-filtered-korea-latest.osm.pbf --expressions=pfaedle-filter-all.txt south-korea-latest.osm.pbf
  
      - name: "Upload South Korea pfaedle filtered"
        env:
          GITHUB_TOKEN: ${{ secrets.GITUHB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: pfaedle-filtered-korea-latest.osm.pbf
          ASSET_NAME: pfaedle-filtered-korea-latest.osm.pbf
          RELEASE_TAG: latest
        run: |
          echo "Uploading asset: $ASSET_PATH as $ASSET_NAME to release latest"
          gh release upload latest "$ASSET_PATH" --clobber
        shell: bash
        if: env.ASSET_PATH != '' && env.ASSET_NAME != ''
