name: Manual Update Trigger

on:
  workflow_dispatch:
    
permissions:
  contents: write
  packages: write

jobs:
  call-update:
    uses: ./.github/workflows/filter.yml
  call-update-norway:
    uses: ./.github/workflows/filter_norway.yml
  call-update-canada:
    uses: ./.github/workflows/filter_canada.yml
  call-update-usa:
    uses: ./.github/workflows/filter_usa.yml
  call-update-india:
    uses: ./.github/workflows/filter_india.yml
  call-update-estonia:
    uses: ./.github/workflows/filter_estonia.yml
  call-update-usa-northeast:
    uses: ./.github/workflows/usa_northeast_filter.yaml
  call-update-japan:
    uses: ./.github/workflows/filter_japan.yml
  call-update-korea:
    uses: ./.github/workflows/filter_korea.yml
  call-update-cta-rail:
    uses: ./.github/workflows/filter_cta_rail.yml
  call-update-ukraine:
    uses: ./.github/workflows/filter_ukraine.yml